### ISSUE TITLE
HookWebpackError: Expecting Unicode escape sequence \uXXXX

### ISSUE THREAD

**Issue by techtruth** [privatenumber/webpack-localize-assets-plugin#49]
## Bug description
During webpack build, I get the error below. I have been using version 1.3.0 because for me this is the latest version that works under my environment. This error is from me attempting to build with latest 1.5.0. 

I suspect this may be something to do with acorn, since 1.3.0 works and the logs say acorn a bunch. :-D But not sure what unicode escape sequence it could be looking for.

## Reproduction steps
Under the environment below, attempt to use the plugin.
Plugin configuration: 
```new LocalizeAssetPlugin({
        locales: {
          en: "webapp/stage/locales/en.json",
          "en-US": "webapp/stage/locales/en.json",
          zh: "webapp/stage/locales/en.json",
          "zh-CN": "webapp/stage/locales/en.json",
          ru: "webapp/stage/locales/en.json",
          "ru-RU": "webapp/stage/locales/en.json",
          fr: "webapp/stage/locales/en.json",
          "fr-FR": "webapp/stage/locales/en.json",
          es: "webapp/stage/locales/es.json",
          "es-ES": "webapp/stage/locales/es.json",
          de: "webapp/stage/locales/en.json",
          "de-DE": "webapp/stage/locales/en.json",
          pt: "webapp/stage/locales/en.json",
          "pt-BR": "webapp/stage/locales/en.json",
          it: "webapp/stage/locales/en.json",
          "it-IT": "webapp/stage/locales/en.json",
          ko: "webapp/stage/locales/ko.json",
          "ko-KR": "webapp/stage/locales/ko.json"
        },
        throwOnMissing: true,
        warnOnUnusedString: true
      })
```
The json files all validate as json as well. Even with english only, this fails.

## Environment

- webpack-localize-asets-plugin version: 1.5.0 (works with 1.3.0)
- Webpack version: 5.39.0
- Operating System: Debian Bullseye (dockerized)
- Node version: LTS 16.14.0
- Package manager (npm/yarn/pnpm) and version: NPM 8.3.1
- Docker https://hub.docker.com/layers/node/library/node/lts-bullseye/images/sha256-0eec05af54bc66646f3b7dc00ae6a8ba52f7ce53ca40df38643f4b432c765534

```
HookWebpackError: Expecting Unicode escape sequence \uXXXX (1:33)
    at makeWebpackError (/container/app/node_modules/webpack/lib/HookWebpackError.js:48:9)
    at /container/app/node_modules/webpack/lib/Compilation.js:2495:12
    at eval (eval at create (/container/app/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:19:1)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
-- inner error --
SyntaxError: Expecting Unicode escape sequence \uXXXX (1:33)
    at Parser.pp$4.raise (/container/app/node_modules/webpack-localize-assets-plugin/node_modules/acorn/dist/acorn.js:3460:15)
    at Parser.pp.invalidStringToken (/container/app/node_modules/webpack-localize-assets-plugin/node_modules/acorn/dist/acorn.js:5349:12)
    at Parser.pp.readWord1 (/container/app/node_modules/webpack-localize-assets-plugin/node_modules/acorn/dist/acorn.js:5515:18)
    at Parser.pp.readWord (/container/app/node_modules/webpack-localize-assets-plugin/node_modules/acorn/dist/acorn.js:5534:21)
    at Parser.pp.readToken (/container/app/node_modules/webpack-localize-assets-plugin/node_modules/acorn/dist/acorn.js:4813:21)
     at Parser.pp.nextToken (/container/app/node_modules/webpack-localize-assets-plugin/node_modules/acorn/dist/acorn.js:4806:17)
     at Parser.pp.next (/container/app/node_modules/webpack-localize-assets-plugin/node_modules/acorn/dist/acorn.js:4767:10)
    at Parser.pp$9.eat (/container/app/node_modules/webpack-localize-assets-plugin/node_modules/acorn/dist/acorn.js:686:12)
    at Parser.pp$5.parseSubscript (/container/app/node_modules/webpack-localize-assets-plugin/node_modules/acorn/dist/acorn.js:2684:33)
    at Parser.pp$5.parseSubscripts (/container/app/node_modules/webpack-localize-assets-plugin/node_modules/acorn/dist/acorn.js:2646:26)
    at Parser.pp$5.parseExprSubscripts (/container/app/node_modules/webpack-localize-assets-plugin/node_modules/acorn/dist/acorn.js:2630:23)
    at Parser.pp$5.parseMaybeUnary (/container/app/node_modules/webpack-localize-assets-plugin/node_modules/acorn/dist/acorn.js:2593:19)
    at Parser.pp$5.parseExprOps (/container/app/node_modules/webpack-localize-assets-plugin/node_modules/acorn/dist/acorn.js:2520:21)
    at Parser.pp$5.parseMaybeConditional (/container/app/node_modules/webpack-localize-assets-plugin/node_modules/acorn/dist/acorn.js:2503:21)
    at Parser.pp$5.parseMaybeAssign (/container/app/node_modules/webpack-localize-assets-plugin/node_modules/acorn/dist/acorn.js:2470:21)
    at Parser.pp$5.parseExprList (/container/app/node_modules/webpack-localize-assets-plugin/node_modules/acorn/dist/acorn.js:3339:20)
caused by plugins in Compilation.hooks.processAssets
SyntaxError: Expecting Unicode escape sequence \uXXXX (1:33)
    at Parser.pp$4.raise (/container/app/node_modules/webpack-localize-assets-plugin/node_modules/acorn/dist/acorn.js:3460:15)
    at Parser.pp.invalidStringToken (/container/app/node_modules/webpack-localize-assets-plugin/node_modules/acorn/dist/acorn.js:5349:12)
    at Parser.pp.readWord1 (/container/app/node_modules/webpack-localize-assets-plugin/node_modules/acorn/dist/acorn.js:5515:18)
    at Parser.pp.readWord (/container/app/node_modules/webpack-localize-assets-plugin/node_modules/acorn/dist/acorn.js:5534:21)
    at Parser.pp.readToken (/container/app/node_modules/webpack-localize-assets-plugin/node_modules/acorn/dist/acorn.js:4813:21)
    at Parser.pp.nextToken (/container/app/node_modules/webpack-localize-assets-plugin/node_modules/acorn/dist/acorn.js:4806:17)
    at Parser.pp.next (/container/app/node_modules/webpack-localize-assets-plugin/node_modules/acorn/dist/acorn.js:4767:10)
    at Parser.pp$9.eat (/container/app/node_modules/webpack-localize-assets-plugin/node_modules/acorn/dist/acorn.js:686:12)
    at Parser.pp$5.parseSubscript (/container/app/node_modules/webpack-localize-assets-plugin/node_modules/acorn/dist/acorn.js:2684:33)
    at Parser.pp$5.parseSubscripts (/container/app/node_modules/webpack-localize-assets-plugin/node_modules/acorn/dist/acorn.js:2646:26)
    at Parser.pp$5.parseExprSubscripts (/container/app/node_modules/webpack-localize-assets-plugin/node_modules/acorn/dist/acorn.js:2630:23)
    at Parser.pp$5.parseMaybeUnary (/container/app/node_modules/webpack-localize-assets-plugin/node_modules/acorn/dist/acorn.js:2593:19)
    at Parser.pp$5.parseExprOps (/container/app/node_modules/webpack-localize-assets-plugin/node_modules/acorn/dist/acorn.js:2520:21)
    at Parser.pp$5.parseMaybeConditional (/container/app/node_modules/webpack-localize-assets-plugin/node_modules/acorn/dist/acorn.js:2503:21)
    at Parser.pp$5.parseMaybeAssign (/container/app/node_modules/webpack-localize-assets-plugin/node_modules/acorn/dist/acorn.js:2470:21)
    at Parser.pp$5.parseExprList (/container/app/node_modules/webpack-localize-assets-plugin/node_modules/acorn/dist/acorn.js:3339:20)
```

**Comment by privatenumber** [comment]
Considering it's an acrons parsing error, it's likely due to something in your code.

Can you provide a minimal reproduction?

**Comment by privatenumber** [comment]
Workarounds are great but I'll need a bug reproduction to get to the root of the problem.

**Comment by xtroncode** [comment]
Hi @privatenumber , here's a minimal repro https://github.com/xtroncode/webpack-localize-assets-issue   it builds with `devtool: false` in the config. 

I also found some other issues:

- strings are not replaced in the dynamically imported modules 
- htmlwebpackplugin outputs only one index.html file. How to get it to output an index file per locale?

**Comment by xtroncode** [comment]
Also when building in `mode: "production"`, a different stack trace is generated
```
Error: Expected BinaryExpression
    at getOriginalCall (IssueReproduction\webpack-localize-assets-issue\node_modules\webpack-localize-assets-plugin
\dist\multi-locale.js:57:15)
    at locatePlaceholders (IssueReproduction\webpack-localize-assets-issue\node_modules\webpack-localize-assets-plu
gin\dist\multi-locale.js:74:19)
    at IssueReproduction\webpack-localize-assets-issue\node_modules\webpack-localize-assets-plugin\dist\multi-local
e.js:150:46
    at Array.map (<anonymous>)
    at generateLocalizedAssetsHandler (IssueReproduction\webpack-localize-assets-issue\node_modules\webpack-localiz
e-assets-plugin\dist\multi-locale.js:145:42)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (IssueReproduction\webpack-localize-assets-issue\node_mo
dules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:6:17)
    at AsyncSeriesHook.lazyCompileHook (IssueReproduction\webpack-localize-assets-issue\node_modules\tapable\lib\Ho
ok.js:154:20)
    at IssueReproduction\webpack-localize-assets-issue\node_modules\webpack\lib\Compilation.js:1414:32
    at eval (eval at create (IssueReproduction\webpack-localize-assets-issue\node_modules\tapable\lib\HookCodeFacto
ry.js:33:10), <anonymous>:9:1)
    at IssueReproduction\webpack-localize-assets-issue\node_modules\terser-webpack-plugin\dist\index.js:321:9
    at step (IssueReproduction\webpack-localize-assets-issue\node_modules\terser-webpack-plugin\dist\TaskRunner.js:
87:9)
    at done (IssueReproduction\webpack-localize-assets-issue\node_modules\terser-webpack-plugin\dist\TaskRunner.js:
98:30)
    at tryCatcher (IssueReproduction\webpack-localize-assets-issue\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (IssueReproduction\webpack-localize-assets-issue\node_modules\bluebird\js\
release\promise.js:547:31)
    at Promise._settlePromise (IssueReproduction\webpack-localize-assets-issue\node_modules\bluebird\js\release\pro
mise.js:604:18)
    at Promise._settlePromise0 (IssueReproduction\webpack-localize-assets-issue\node_modules\bluebird\js\release\pr
omise.js:649:10)
    at Promise._settlePromises (IssueReproduction\webpack-localize-assets-issue\node_modules\bluebird\js\release\pr
omise.js:729:18)
    at Promise._fulfill (IssueReproduction\webpack-localize-assets-issue\node_modules\bluebird\js\release\promise.j
s:673:18)
    at Promise._resolveCallback (IssueReproduction\webpack-localize-assets-issue\node_modules\bluebird\js\release\p
romise.js:466:57)
    at Promise._settlePromiseFromHandler (IssueReproduction\webpack-localize-assets-issue\node_modules\bluebird\js\
release\promise.js:559:17)
    at Promise._settlePromise (IssueReproduction\webpack-localize-assets-issue\node_modules\bluebird\js\release\pro
mise.js:604:18)
    at Promise._settlePromise0 (IssueReproduction\webpack-localize-assets-issue\node_modules\bluebird\js\release\pr
omise.js:649:10)
    at Promise._settlePromises (IssueReproduction\webpack-localize-assets-issue\node_modules\bluebird\js\release\pr
omise.js:729:18)
    at Promise._fulfill (IssueReproduction\webpack-localize-assets-issue\node_modules\bluebird\js\release\promise.j
s:673:18)
    at Promise._resolveCallback (IssueReproduction\webpack-localize-assets-issue\node_modules\bluebird\js\release\p
romise.js:466:57)
    at Promise._settlePromiseFromHandler (IssueReproduction\webpack-localize-assets-issue\node_modules\bluebird\js\
release\promise.js:559:17)
    at Promise._settlePromise (IssueReproduction\webpack-localize-assets-issue\node_modules\bluebird\js\release\pro
mise.js:604:18)
    at Promise._settlePromise0 (IssueReproduction\webpack-localize-assets-issue\node_modules\bluebird\js\release\pr
omise.js:649:10)
    at Promise._settlePromises (IssueReproduction\webpack-localize-assets-issue\node_modules\bluebird\js\release\pr
omise.js:729:18)
    at Promise._fulfill (IssueReproduction\webpack-localize-assets-issue\node_modules\bluebird\js\release\promise.j
s:673:18)
    at Promise._settlePromise (IssueReproduction\webpack-localize-assets-issue\node_modules\bluebird\js\release\pro
mise.js:617:21)
    at Promise._settlePromise0 (IssueReproduction\webpack-localize-assets-issue\node_modules\bluebird\js\release\pr
omise.js:649:10)
    at Promise._settlePromises (IssueReproduction\webpack-localize-assets-issue\node_modules\bluebird\js\release\pr
omise.js:729:18)
    at Promise._fulfill (IssueReproduction\webpack-localize-assets-issue\node_modules\bluebird\js\release\promise.j
s:673:18)
    at Promise._resolveCallback (IssueReproduction\webpack-localize-assets-issue\node_modules\bluebird\js\release\p
romise.js:489:14)
    at Promise._settlePromiseFromHandler (IssueReproduction\webpack-localize-assets-issue\node_modules\bluebird\js\
release\promise.js:559:17)
```

**Comment by privatenumber** [comment]
Thanks for the reproduction @xtroncode 

I fixed both issues in https://github.com/privatenumber/webpack-localize-assets-plugin/releases/tag/v1.5.1

**Comment by xtroncode** [comment]
Hi @privatenumber , the build output in case of `devtool: "eval-cheap-module-source-map"` still has issues, it builds successfully but the output has syntax errors, this can be reproduced in the same repo by using this value for the devtool config. Thanks.

**Comment by privatenumber** [comment]
Thanks. I won't have time for it this week, but feel free to take a stab at it based on the PR referenced above.

**Comment by xtroncode** [comment]
I tried analysing this ,
The current output is 
```
/***/ (function(module, exports) {

eval("const hell = "Hello!";//# sourceURL=[module]\n//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiLi9zcmMvaW5kZXguanMuanMiLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9zcmMvaW5kZXguanM/YjYzNSJdLCJzb3VyY2VzQ29udGVudCI6WyJjb25zdCBoZWxsID0gX18oXCJoZWxsb1wiKTtcclxuIl0sIm1hcHBpbmdzIjoiQUFBQSIsInNvdXJjZVJvb3QiOiIifQ==\n//# sourceURL=webpack-internal:///./src/index.js\n");

/***/ })
```

Notice that the quotes in the code around `"Hello"` are not escaped and hence is a syntax error

So I figured that the issue is where the localized value is being injected

I made changes to `multi-locale.ts` >`localizeAsset` method
```diff
magicStringInstance.overwrite(
			range.start,
			range.end!,
-			localizedCode,
+                       localizedCode.replace(/"/g,'\\"'),
		);
```

The above change fixes the issue for `eval*` devtools with the folowing output
```
/***/ (function(module, exports) {

eval("const hell = \"Hello!\";//# sourceURL=[module]\n//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiLi9zcmMvaW5kZXguanMuanMiLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9zcmMvaW5kZXguanM/YjYzNSJdLCJzb3VyY2VzQ29udGVudCI6WyJjb25zdCBoZWxsID0gX18oXCJoZWxsb1wiKTtcclxuIl0sIm1hcHBpbmdzIjoiQUFBQSIsInNvdXJjZVJvb3QiOiIifQ==\n//# sourceURL=webpack-internal:///./src/index.js\n");

/***/ })
```

But this breaks the output for other cases of devtools. I think I might have to make a decision based on the type of devtools option selected. I could find how to get the selected devtool option from the compilation object. @privatenumber  is this the correct approach? If yes, can you give some pointers on how to get the selected devtool configuration. If this is not the correct approach, what else can I try?

Thanks.

**Comment by xtroncode** [comment]
Hi @privatenumber can you help with the above query?

**Comment by privatenumber** [comment]
@xtroncode 

Can you open a PR with a failing test? I will take a look there

**Comment by xtroncode** [comment]
@privatenumber I have opened PR #52 with a failing test due to this issue.

**Comment by privatenumber** [comment]
Thanks for the reproduction @xtroncode . I thought you were talking about quotes in the actual key rather than the value, so this reproduction was helpful even though it feels quite obvious now 😅
